/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-26 05:04:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.recruiter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addJob_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Recuiter - Add Job</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"<c:url value = '/all-component/all-css.jsp'/>\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #f0f1f2;\">\r\n");
      out.write("	<div class=\"container p-2\">\r\n");
      out.write("		<div class=\"col-md-10 offset-md-1\">\r\n");
      out.write("			<div class=\"card\">\r\n");
      out.write("				<div class=\"card-body\">\r\n");
      out.write("					<div class=\"text-center text-success\">\r\n");
      out.write("						<i class=\"fas fa-user-friends fa-3x\"></i>\r\n");
      out.write("						<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty succMsg }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("							<div class=\"alert alert-success\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ succMsg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("							<c:remove var=\"succMsg\" />\r\n");
      out.write("						</c:if> \r\n");
      out.write("\r\n");
      out.write("						<h5>Add Jobs</h5>\r\n");
      out.write("					</div>\r\n");
      out.write("					<form action=\"recruiter-add-job\" method=\"post\">\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Enter Title</label> <input type=\"text\" name=\"title\"\r\n");
      out.write("								required class=\"from-control\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-row\">\r\n");
      out.write("							<div class=\"form-group col-md-4\">\r\n");
      out.write("								<label>Location</label> <select name=\"location\"\r\n");
      out.write("									class=\"custom-select\" id=\"inlineFormCustomSelectPref\">\r\n");
      out.write("									<option>Choose..</option>\r\n");
      out.write("\r\n");
      out.write("									<option value=\"AnGiang\">An Giang</option>\r\n");
      out.write("									<option value=\"BaRia-Vung Tau\">Ba Ria - Vung Tau</option>\r\n");
      out.write("									<option value=\"BacGiang\">Bac Giang</option>\r\n");
      out.write("									<option value=\"BacKan\">Bac Kan</option>\r\n");
      out.write("									<option value=\"BacLieu\">Bac Lieu</option>\r\n");
      out.write("									<option value=\"BacNinh\">Bac Ninh</option>\r\n");
      out.write("									<option value=\"BenTre\">Ben Tre</option>\r\n");
      out.write("									<option value=\"BinhDinh\">Binh Dinh</option>\r\n");
      out.write("									<option value=\"BinhDuong\">Binh Duong</option>\r\n");
      out.write("									<option value=\"BinhPhuoc\">Binh Phuoc</option>\r\n");
      out.write("									<option value=\"BinhThuan\">Binh Thuan</option>\r\n");
      out.write("									<option value=\"CaMau\">Ca Mau</option>\r\n");
      out.write("									<option value=\"CanTho\">Can Tho</option>\r\n");
      out.write("									<option value=\"CaoBang\">Cao Bang</option>\r\n");
      out.write("									<option value=\"DaNang\">Da Nang</option>\r\n");
      out.write("									<option value=\"DakLak\">Dak Lak</option>\r\n");
      out.write("									<option value=\"DakNong\">Dak Nong</option>\r\n");
      out.write("									<option value=\"DienBien\">Dien Bien</option>\r\n");
      out.write("									<option value=\"DongNai\">Dong Nai</option>\r\n");
      out.write("									<option value=\"DongThap\">Dong Thap</option>\r\n");
      out.write("									<option value=\"GiaLai\">Gia Lai</option>\r\n");
      out.write("									<option value=\"HaGiang\">Ha Giang</option>\r\n");
      out.write("									<option value=\"HaNoi\">Ha Noi</option>\r\n");
      out.write("									<option value=\"HaTinh\">Ha Tinh</option>\r\n");
      out.write("									<option value=\"HaiDuong\">Hai Duong</option>\r\n");
      out.write("									<option value=\"HaiPhong\">Hai Phong</option>\r\n");
      out.write("									<option value=\"HauGiang\">Hau Giang</option>\r\n");
      out.write("									<option value=\"HoChiMinhCity\">Ho Chi Minh City</option>\r\n");
      out.write("									<option value=\"HauGiang\">Hau Giang</option>\r\n");
      out.write("									<option value=\"HoaBinh\">Hoa Binh</option>\r\n");
      out.write("									<option value=\"HungYen\">Hung Yen</option>\r\n");
      out.write("									<option value=\"KhanhHoa\">Khanh Hoa</option>\r\n");
      out.write("									<option value=\"KienGiang\">Kien Giang</option>\r\n");
      out.write("									<option value=\"KonTum\">Kon Tum</option>\r\n");
      out.write("									<option value=\"LaiChau\">Lai Chau</option>\r\n");
      out.write("									<option value=\"LamDong\">Lam Dong</option>\r\n");
      out.write("									<option value=\"LangSon\">Lang Son</option>\r\n");
      out.write("									<option value=\"LaoCai\">Lao Cai</option>\r\n");
      out.write("									<option value=\"LongAn\">Long An</option>\r\n");
      out.write("									<option value=\"NamDinh\">Nam Dinh</option>\r\n");
      out.write("									<option value=\"NgheAn\">Nghe An</option>\r\n");
      out.write("									<option value=\"NinhBinh\">Ninh Binh</option>\r\n");
      out.write("									<option value=\"NinhThuan\">Ninh Thuan</option>\r\n");
      out.write("									<option value=\"PhuTho\">Phu Tho</option>\r\n");
      out.write("									<option value=\"PhuYen\">Phu Yen</option>\r\n");
      out.write("									<option value=\"QuangBinh\">Quang Binh</option>\r\n");
      out.write("									<option value=\"QuangNam\">Quang Nam</option>\r\n");
      out.write("									<option value=\"QuangNgai\">Quang Ngai</option>\r\n");
      out.write("									<option value=\"QuangNinh\">Quang Ninh</option>\r\n");
      out.write("									<option value=\"QuangTri\">Quang Tri</option>\r\n");
      out.write("									<option value=\"SocTrang\">Soc Trang</option>\r\n");
      out.write("									<option value=\"SonLa\">Son La</option>\r\n");
      out.write("									<option value=\"Tay Ninh\">Tay Ninh</option>\r\n");
      out.write("									<option value=\"ThaiBinh\">Thai Binh</option>\r\n");
      out.write("									<option value=\"ThaiNguyen\">Thai Nguyen</option>\r\n");
      out.write("									<option value=\"ThanhHoa\">Thanh Hoa</option>\r\n");
      out.write("									<option value=\"ThuaThien-Hue\">Thua Thien-Hue</option>\r\n");
      out.write("									<option value=\"TienGiang\">Tien Giang</option>\r\n");
      out.write("									<option value=\"TraVinh\">Tra Vinh</option>\r\n");
      out.write("									<option value=\"TuyenQuang\">Tuyen Quang</option>\r\n");
      out.write("									<option value=\"VinhLong\">Vinh Long</option>\r\n");
      out.write("									<option value=\"VinhPhuc\">Vinh Phuc</option>\r\n");
      out.write("									<option value=\"YenBai\">Yen Bai</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group col-md-4\">\r\n");
      out.write("								<label>Category</label> <select class=\"custom-select\"\r\n");
      out.write("									id=\"inlineFormCustomSelectPref\" name=\"category\">\r\n");
      out.write("									<option value=\"Developer\">Developer</option>\r\n");
      out.write("									<option value=\"Designer\">Designer</option>\r\n");
      out.write("									<option value=\"Engineer\">Engineer</option>\r\n");
      out.write("									<option value=\"Manager\">Manager</option>\r\n");
      out.write("									<option value=\"Analyst\">Analyst</option>\r\n");
      out.write("									<option value=\"Consultant\">Consultant</option>\r\n");
      out.write("									<option value=\"Marketing\">Marketing</option>\r\n");
      out.write("									<option value=\"Sales\">Sales</option>\r\n");
      out.write("									<option value=\"Customer Service\">Customer Service</option>\r\n");
      out.write("									<option value=\"Finance\">Finance</option>\r\n");
      out.write("									<option value=\"Human Resources\">Human Resources</option>\r\n");
      out.write("									<option value=\"Healthcare\">Healthcare</option>\r\n");
      out.write("									<option value=\"Education\">Education</option>\r\n");
      out.write("									<option value=\"Legal\">Legal</option>\r\n");
      out.write("									<option value=\"Hospitality\">Hospitality</option>\r\n");
      out.write("									<option value=\"Retail\">Retail</option>\r\n");
      out.write("									<option value=\"Manufacturing\">Manufacturing</option>\r\n");
      out.write("									<option value=\"Construction\">Construction</option>\r\n");
      out.write("									<option value=\"Transportation\">Transportation</option>\r\n");
      out.write("									<option value=\"Logistics\">Logistics</option>\r\n");
      out.write("									<option value=\"Supply Chain\">Supply Chain</option>\r\n");
      out.write("									<option value=\"Administration\">Administration</option>\r\n");
      out.write("									<option value=\"Information Technology\">Information\r\n");
      out.write("										Technology</option>\r\n");
      out.write("									<option value=\"Data Science\">Data Science</option>\r\n");
      out.write("									<option value=\"Cybersecurity\">Cybersecurity</option>\r\n");
      out.write("									<option value=\"Network Administration\">Network\r\n");
      out.write("										Administration</option>\r\n");
      out.write("									<option value=\"System Administration\">System\r\n");
      out.write("										Administration</option>\r\n");
      out.write("									<option value=\"Cloud Computing\">Cloud Computing</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"form-group col-md-4\">\r\n");
      out.write("								<label>Status</label> <select class=\"form-control\" name=\"status\">\r\n");
      out.write("									<option class=\"Active\" value=\"Active\">Active</option>\r\n");
      out.write("									<option class=\"Inactive\" value=\"Inactive\">Inactive</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"form-group\">\r\n");
      out.write("							<label>Enter Description</label>\r\n");
      out.write("							<textarea rows=\"6\" cols=\"\" name=\"desc\" class=\"from-control\"></textarea>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button class=\"btn btn-success\">Publish Job</button>\r\n");
      out.write("					</form>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
