/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-04 17:29:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/PBL3/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/PBL3/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1712144786899L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1711982526419L));
    _jspx_dependants.put("jar:file:/D:/PBL3/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/PBL3/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1712141790945L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Job Portal</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<main> <!-- Hero Area Start-->\r\n");
      out.write("	<div class=\"slider-area \">\r\n");
      out.write("		<div\r\n");
      out.write("			class=\"single-slider section-overly slider-height2 d-flex align-items-center\"\r\n");
      out.write("			data-background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/hero/about.jpg\">\r\n");
      out.write("			<div class=\"container\">\r\n");
      out.write("				<div class=\"row\">\r\n");
      out.write("					<div class=\"col-xl-12\">\r\n");
      out.write("						<div class=\"hero-cap text-center\">\r\n");
      out.write("							<h2>About us</h2>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Hero Area End --> <!-- Support Company Start-->\r\n");
      out.write("	<div class=\"support-company-area fix section-padding2\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center\">\r\n");
      out.write("				<div class=\"col-xl-6 col-lg-6\">\r\n");
      out.write("					<div class=\"right-caption\">\r\n");
      out.write("						<!-- Section Tittle -->\r\n");
      out.write("						<div class=\"section-tittle section-tittle2\">\r\n");
      out.write("							<span>What we are doing</span>\r\n");
      out.write("							<h2>24k Talented people are getting Jobs</h2>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"support-caption\">\r\n");
      out.write("							<p class=\"pera-top\">Mollit anim laborum duis au dolor in\r\n");
      out.write("								voluptate velit ess cillum dolore eu lore dsu quality mollit\r\n");
      out.write("								anim laborumuis au dolor in voluptate velit cillum.</p>\r\n");
      out.write("							<p>Mollit anim laborum.Duis aute irufg dhjkolohr in re\r\n");
      out.write("								voluptate velit esscillumlore eu quife nrulla parihatur.\r\n");
      out.write("								Excghcepteur signjnt occa cupidatat non inulpadeserunt mollit\r\n");
      out.write("								aboru. temnthp incididbnt ut labore mollit anim laborum suis\r\n");
      out.write("								aute.</p>\r\n");
      out.write("							<a href=\"about.html\" class=\"btn post-btn\">Post a job</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-6 col-lg-6\">\r\n");
      out.write("					<div class=\"support-location-img\">\r\n");
      out.write("						<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/service/support-img.jpg\" alt=\"\">\r\n");
      out.write("						<div class=\"support-img-cap text-center\">\r\n");
      out.write("							<p>Since</p>\r\n");
      out.write("							<span>1994</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Support Company End--> <!-- How  Apply Process Start-->\r\n");
      out.write("	<div class=\"apply-process-area apply-bg pt-150 pb-150\"\r\n");
      out.write("		data-background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/gallery/how-applybg.png\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Section Tittle -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"section-tittle white-text text-center\">\r\n");
      out.write("						<span>Apply process</span>\r\n");
      out.write("						<h2>How it works</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Apply Process Caption -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("					<div class=\"single-process text-center mb-30\">\r\n");
      out.write("						<div class=\"process-ion\">\r\n");
      out.write("							<span class=\"flaticon-search\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"process-cap\">\r\n");
      out.write("							<h5>1. Search a job</h5>\r\n");
      out.write("							<p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod\r\n");
      out.write("								tempor incididunt ut laborea.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("					<div class=\"single-process text-center mb-30\">\r\n");
      out.write("						<div class=\"process-ion\">\r\n");
      out.write("							<span class=\"flaticon-curriculum-vitae\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"process-cap\">\r\n");
      out.write("							<h5>2. Apply for job</h5>\r\n");
      out.write("							<p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod\r\n");
      out.write("								tempor incididunt ut laborea.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("					<div class=\"single-process text-center mb-30\">\r\n");
      out.write("						<div class=\"process-ion\">\r\n");
      out.write("							<span class=\"flaticon-tour\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"process-cap\">\r\n");
      out.write("							<h5>3. Get your job</h5>\r\n");
      out.write("							<p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod\r\n");
      out.write("								tempor incididunt ut laborea.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- How  Apply Process End--> <!-- Testimonial Start -->\r\n");
      out.write("	<div class=\"testimonial-area testimonial-padding\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Testimonial contents -->\r\n");
      out.write("			<div class=\"row d-flex justify-content-center\">\r\n");
      out.write("				<div class=\"col-xl-8 col-lg-8 col-md-10\">\r\n");
      out.write("					<div class=\"h1-testimonial-active dot-style\">\r\n");
      out.write("						<!-- Single Testimonial -->\r\n");
      out.write("						<div class=\"single-testimonial text-center\">\r\n");
      out.write("							<!-- Testimonial Content -->\r\n");
      out.write("							<div class=\"testimonial-caption \">\r\n");
      out.write("								<!-- founder -->\r\n");
      out.write("								<div class=\"testimonial-founder  \">\r\n");
      out.write("									<div class=\"founder-img mb-30\">\r\n");
      out.write("										<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/testmonial/testimonial-founder.png\"\r\n");
      out.write("											alt=\"\"> <span>Margaret Lawson</span>\r\n");
      out.write("										<p>Creative Director</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"testimonial-top-cap\">\r\n");
      out.write("									<p>“I am at an age where I just want to be fit and healthy\r\n");
      out.write("										our bodies are our responsibility! So start caring for your\r\n");
      out.write("										body and it will care for you. Eat clean it will care for you\r\n");
      out.write("										and workout hard.”</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Single Testimonial -->\r\n");
      out.write("						<div class=\"single-testimonial text-center\">\r\n");
      out.write("							<!-- Testimonial Content -->\r\n");
      out.write("							<div class=\"testimonial-caption \">\r\n");
      out.write("								<!-- founder -->\r\n");
      out.write("								<div class=\"testimonial-founder  \">\r\n");
      out.write("									<div class=\"founder-img mb-30\">\r\n");
      out.write("										<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/testmonial/testimonial-founder.png\"\r\n");
      out.write("											alt=\"\"> <span>Margaret Lawson</span>\r\n");
      out.write("										<p>Creative Director</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"testimonial-top-cap\">\r\n");
      out.write("									<p>“I am at an age where I just want to be fit and healthy\r\n");
      out.write("										our bodies are our responsibility! So start caring for your\r\n");
      out.write("										body and it will care for you. Eat clean it will care for you\r\n");
      out.write("										and workout hard.”</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Single Testimonial -->\r\n");
      out.write("						<div class=\"single-testimonial text-center\">\r\n");
      out.write("							<!-- Testimonial Content -->\r\n");
      out.write("							<div class=\"testimonial-caption \">\r\n");
      out.write("								<!-- founder -->\r\n");
      out.write("								<div class=\"testimonial-founder  \">\r\n");
      out.write("									<div class=\"founder-img mb-30\">\r\n");
      out.write("										<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/testmonial/testimonial-founder.png\"\r\n");
      out.write("											alt=\"\"> <span>Margaret Lawson</span>\r\n");
      out.write("										<p>Creative Director</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"testimonial-top-cap\">\r\n");
      out.write("									<p>“I am at an age where I just want to be fit and healthy\r\n");
      out.write("										our bodies are our responsibility! So start caring for your\r\n");
      out.write("										body and it will care for you. Eat clean it will care for you\r\n");
      out.write("										and workout hard.”</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Testimonial End --> <!-- Online CV Area Start -->\r\n");
      out.write("	<div class=\"online-cv cv-bg section-overly pt-90 pb-120\"\r\n");
      out.write("		data-background=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/gallery/cv_bg.jpg\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("				<div class=\"col-xl-10\">\r\n");
      out.write("					<div class=\"cv-caption text-center\">\r\n");
      out.write("						<p class=\"pera1\">FEATURED TOURS Packages</p>\r\n");
      out.write("						<p class=\"pera2\">Make a Difference with Your Online Resume!</p>\r\n");
      out.write("						<a href=\"#\" class=\"border-btn2 border-btn4\">Upload your cv</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Online CV Area End--> <!-- Blog Area Start -->\r\n");
      out.write("	<div class=\"home-blog-area blog-h-padding\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Section Tittle -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"section-tittle text-center\">\r\n");
      out.write("						<span>Our latest blog</span>\r\n");
      out.write("						<h2>Our recent news</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-xl-6 col-lg-6 col-md-6\">\r\n");
      out.write("					<div class=\"home-blog-single mb-30\">\r\n");
      out.write("						<div class=\"blog-img-cap\">\r\n");
      out.write("							<div class=\"blog-img\">\r\n");
      out.write("								<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/blog/home-blog1.jpg\" alt=\"\">\r\n");
      out.write("								<!-- Blog date -->\r\n");
      out.write("								<div class=\"blog-date text-center\">\r\n");
      out.write("									<span>24</span>\r\n");
      out.write("									<p>Now</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"blog-cap\">\r\n");
      out.write("								<p>| Properties</p>\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"single-blog.html\">Footprints in Time is perfect\r\n");
      out.write("										House in Kurashiki</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<a href=\"#\" class=\"more-btn\">Read more »</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-6 col-lg-6 col-md-6\">\r\n");
      out.write("					<div class=\"home-blog-single mb-30\">\r\n");
      out.write("						<div class=\"blog-img-cap\">\r\n");
      out.write("							<div class=\"blog-img\">\r\n");
      out.write("								<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/blog/home-blog2.jpg\" alt=\"\">\r\n");
      out.write("								<!-- Blog date -->\r\n");
      out.write("								<div class=\"blog-date text-center\">\r\n");
      out.write("									<span>24</span>\r\n");
      out.write("									<p>Now</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"blog-cap\">\r\n");
      out.write("								<p>| Properties</p>\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"single-blog.html\">Footprints in Time is perfect\r\n");
      out.write("										House in Kurashiki</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<a href=\"#\" class=\"more-btn\">Read more »</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Blog Area End --> </main>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
