/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-04-04 17:29:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/PBL3/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/PBL3/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1712144786899L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1711982526419L));
    _jspx_dependants.put("jar:file:/D:/PBL3/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/PBL3/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1712141790945L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Job Portal</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"slider-area \">\r\n");
      out.write("		<!-- Mobile Menu -->\r\n");
      out.write("		<div class=\"slider-active\">\r\n");
      out.write("			<div class=\"single-slider slider-height d-flex align-items-center\"\r\n");
      out.write("				data-background=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("				<div class=\"container\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-xl-6 col-lg-9 col-md-10\">\r\n");
      out.write("							<div class=\"hero__caption\">\r\n");
      out.write("								<h1>Find the most exciting startup jobs</h1>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Search Box -->\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-xl-8\">\r\n");
      out.write("							<!-- form\r\n");
      out.write("							<form action=\"#\" class=\"search-box\">\r\n");
      out.write("								<div class=\"input-form\">\r\n");
      out.write("									<input type=\"text\" placeholder=\"Job Tittle or keyword\">\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"select-form\">\r\n");
      out.write("									<div class=\"select-itms\">\r\n");
      out.write("										<select name=\"select\" id=\"select1\">\r\n");
      out.write("											<option value=\"\">Location BD</option>\r\n");
      out.write("											<option value=\"\">Location PK</option>\r\n");
      out.write("											<option value=\"\">Location US</option>\r\n");
      out.write("											<option value=\"\">Location UK</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"search-form\">\r\n");
      out.write("									<a href=\"#\">Find job</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</form\r\n");
      out.write("							-->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- slider Area End--> <!-- Our Services Start -->\r\n");
      out.write("	<div class=\"our-services section-pad-t30\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Section Tittle -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"section-tittle text-center\">\r\n");
      out.write("						<span>FEATURED TOURS Packages</span>\r\n");
      out.write("						<h2>Browse Top Categories</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row d-flex justify-contnet-center\">\r\n");
      out.write("				<div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("					<div class=\"single-services text-center mb-30\">\r\n");
      out.write("						<div class=\"services-ion\">\r\n");
      out.write("							<span class=\"flaticon-tour\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"services-cap\">\r\n");
      out.write("							<h5>\r\n");
      out.write("								<a href=\"job_listing.html\">Design &amp; Creative</a>\r\n");
      out.write("							</h5>\r\n");
      out.write("							<span>(653)</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("					<div class=\"single-services text-center mb-30\">\r\n");
      out.write("						<div class=\"services-ion\">\r\n");
      out.write("							<span class=\"flaticon-cms\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"services-cap\">\r\n");
      out.write("							<h5>\r\n");
      out.write("								<a href=\"job_listing.html\">Design &amp; Development</a>\r\n");
      out.write("							</h5>\r\n");
      out.write("							<span>(658)</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("					<div class=\"single-services text-center mb-30\">\r\n");
      out.write("						<div class=\"services-ion\">\r\n");
      out.write("							<span class=\"flaticon-report\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"services-cap\">\r\n");
      out.write("							<h5>\r\n");
      out.write("								<a href=\"job_listing.html\">Sales &amp; Marketing</a>\r\n");
      out.write("							</h5>\r\n");
      out.write("							<span>(658)</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("					<div class=\"single-services text-center mb-30\">\r\n");
      out.write("						<div class=\"services-ion\">\r\n");
      out.write("							<span class=\"flaticon-app\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"services-cap\">\r\n");
      out.write("							<h5>\r\n");
      out.write("								<a href=\"job_listing.html\">Mobile Application</a>\r\n");
      out.write("							</h5>\r\n");
      out.write("							<span>(658)</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("					<div class=\"single-services text-center mb-30\">\r\n");
      out.write("						<div class=\"services-ion\">\r\n");
      out.write("							<span class=\"flaticon-helmet\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"services-cap\">\r\n");
      out.write("							<h5>\r\n");
      out.write("								<a href=\"job_listing.html\">Construction</a>\r\n");
      out.write("							</h5>\r\n");
      out.write("							<span>(658)</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("					<div class=\"single-services text-center mb-30\">\r\n");
      out.write("						<div class=\"services-ion\">\r\n");
      out.write("							<span class=\"flaticon-high-tech\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"services-cap\">\r\n");
      out.write("							<h5>\r\n");
      out.write("								<a href=\"job_listing.html\">Information Technology</a>\r\n");
      out.write("							</h5>\r\n");
      out.write("							<span>(658)</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("					<div class=\"single-services text-center mb-30\">\r\n");
      out.write("						<div class=\"services-ion\">\r\n");
      out.write("							<span class=\"flaticon-real-estate\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"services-cap\">\r\n");
      out.write("							<h5>\r\n");
      out.write("								<a href=\"job_listing.html\">Real Estate</a>\r\n");
      out.write("							</h5>\r\n");
      out.write("							<span>(658)</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-3 col-lg-3 col-md-4 col-sm-6\">\r\n");
      out.write("					<div class=\"single-services text-center mb-30\">\r\n");
      out.write("						<div class=\"services-ion\">\r\n");
      out.write("							<span class=\"flaticon-content\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"services-cap\">\r\n");
      out.write("							<h5>\r\n");
      out.write("								<a href=\"job_listing.html\">Content Writer</a>\r\n");
      out.write("							</h5>\r\n");
      out.write("							<span>(658)</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- More Btn -->\r\n");
      out.write("			<!-- Section Button -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"browse-btn2 text-center mt-50\">\r\n");
      out.write("						<a href=\"job_listing.html\" class=\"border-btn2\">Browse All\r\n");
      out.write("							Sectors</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Our Services End --> <!-- Online CV Area Start -->\r\n");
      out.write("	<div class=\"online-cv cv-bg section-overly pt-90 pb-120\"\r\n");
      out.write("		data-background=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("				<div class=\"col-xl-10\">\r\n");
      out.write("					<div class=\"cv-caption text-center\">\r\n");
      out.write("						<p class=\"pera1\">FEATURED TOURS Packages</p>\r\n");
      out.write("						<p class=\"pera2\">Make a Difference with Your Online Resume!</p>\r\n");
      out.write("						<a href=\"#\" class=\"border-btn2 border-btn4\">Upload your cv</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Online CV Area End--> <!-- Featured_job_start -->\r\n");
      out.write("	<section class=\"featured-job-area feature-padding\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Section Tittle -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"section-tittle text-center\">\r\n");
      out.write("						<span>Recent Job</span>\r\n");
      out.write("						<h2>Featured Jobs</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row justify-content-center\">\r\n");
      out.write("				<div class=\"col-xl-10\">\r\n");
      out.write("					<!-- single-job-content -->\r\n");
      out.write("					<div class=\"single-job-items mb-30\">\r\n");
      out.write("						<div class=\"job-items\">\r\n");
      out.write("							<div class=\"company-img\">\r\n");
      out.write("								<a href=\"job_details.html\"><img\r\n");
      out.write("									src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" alt=\"\"/></a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"job-tittle\">\r\n");
      out.write("								<h4><a href=\"job_details.html\">Digital Marketer</a></h4>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li>Creative Agency</li>\r\n");
      out.write("									<li><i class=\"fas fa-map-marker-alt\"></i>Athens, Greece</li>\r\n");
      out.write("									<li>$3500 - $4000</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"items-link f-right\">\r\n");
      out.write("							<a href=\"job_details.html\">Full Time</a> <span>7 hours ago</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- single-job-content -->\r\n");
      out.write("					<div class=\"single-job-items mb-30\">\r\n");
      out.write("						<div class=\"job-items\">\r\n");
      out.write("							<div class=\"company-img\">\r\n");
      out.write("								<a href=\"job_details.html\"><img\r\n");
      out.write("									src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" alt=\"\"/></a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"job-tittle\">\r\n");
      out.write("								<h4><a href=\"job_details.html\">Digital Marketer</a></h4>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li>Creative Agency</li>\r\n");
      out.write("									<li><i class=\"fas fa-map-marker-alt\"></i>Athens, Greece</li>\r\n");
      out.write("									<li>$3500 - $4000</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"items-link f-right\">\r\n");
      out.write("							<a href=\"job_details.html\">Full Time</a> <span>7 hours ago</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- single-job-content -->\r\n");
      out.write("					<div class=\"single-job-items mb-30\">\r\n");
      out.write("						<div class=\"job-items\">\r\n");
      out.write("							<div class=\"company-img\">\r\n");
      out.write("								<a href=\"job_details.html\"><img\r\n");
      out.write("									src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" alt=\"\"/></a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"job-tittle\">\r\n");
      out.write("								<h4><a href=\"job_details.html\">Digital Marketer</a></h4>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li>Creative Agency</li>\r\n");
      out.write("									<li><i class=\"fas fa-map-marker-alt\"></i>Athens, Greece</li>\r\n");
      out.write("									<li>$3500 - $4000</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"items-link f-right\">\r\n");
      out.write("							<a href=\"job_details.html\">Full Time</a> <span>7 hours ago</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- single-job-content -->\r\n");
      out.write("					<div class=\"single-job-items mb-30\">\r\n");
      out.write("						<div class=\"job-items\">\r\n");
      out.write("							<div class=\"company-img\">\r\n");
      out.write("								<a href=\"job_details.html\"><img\r\n");
      out.write("									src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" alt=\"\"/></a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"job-tittle\">\r\n");
      out.write("								<h4><a href=\"job_details.html\">Digital Marketer</a></h4>\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li>Creative Agency</li>\r\n");
      out.write("									<li><i class=\"fas fa-map-marker-alt\"></i>Athens, Greece</li>\r\n");
      out.write("									<li>$3500 - $4000</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"items-link f-right\">\r\n");
      out.write("							<a href=\"job_details.html\">Full Time</a> <span>7 hours ago</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<!-- Featured_job_end --> <!-- How  Apply Process Start-->\r\n");
      out.write("	<div class=\"apply-process-area apply-bg pt-150 pb-150\"\r\n");
      out.write("		data-background=\"");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Section Tittle -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"section-tittle white-text text-center\">\r\n");
      out.write("						<span>Apply process</span>\r\n");
      out.write("						<h2>How it works</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- Apply Process Caption -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("					<div class=\"single-process text-center mb-30\">\r\n");
      out.write("						<div class=\"process-ion\">\r\n");
      out.write("							<span class=\"flaticon-search\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"process-cap\">\r\n");
      out.write("							<h5>1. Search a job</h5>\r\n");
      out.write("							<p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod\r\n");
      out.write("								tempor incididunt ut laborea.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("					<div class=\"single-process text-center mb-30\">\r\n");
      out.write("						<div class=\"process-ion\">\r\n");
      out.write("							<span class=\"flaticon-curriculum-vitae\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"process-cap\">\r\n");
      out.write("							<h5>2. Apply for job</h5>\r\n");
      out.write("							<p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod\r\n");
      out.write("								tempor incididunt ut laborea.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-4 col-md-6\">\r\n");
      out.write("					<div class=\"single-process text-center mb-30\">\r\n");
      out.write("						<div class=\"process-ion\">\r\n");
      out.write("							<span class=\"flaticon-tour\"></span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"process-cap\">\r\n");
      out.write("							<h5>3. Get your job</h5>\r\n");
      out.write("							<p>Sorem spsum dolor sit amsectetur adipisclit, seddo eiusmod\r\n");
      out.write("								tempor incididunt ut laborea.</p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- How  Apply Process End--> <!-- Testimonial Start -->\r\n");
      out.write("	<div class=\"testimonial-area testimonial-padding\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Testimonial contents -->\r\n");
      out.write("			<div class=\"row d-flex justify-content-center\">\r\n");
      out.write("				<div class=\"col-xl-8 col-lg-8 col-md-10\">\r\n");
      out.write("					<div class=\"h1-testimonial-active dot-style\">\r\n");
      out.write("						<!-- Single Testimonial -->\r\n");
      out.write("						<div class=\"single-testimonial text-center\">\r\n");
      out.write("							<!-- Testimonial Content -->\r\n");
      out.write("							<div class=\"testimonial-caption \">\r\n");
      out.write("								<!-- founder -->\r\n");
      out.write("								<div class=\"testimonial-founder  \">\r\n");
      out.write("									<div class=\"founder-img mb-30\">\r\n");
      out.write("										<img src=\"");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("											alt=\"\"/> <span>Margaret Lawson</span>\r\n");
      out.write("										<p>Creative Director</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"testimonial-top-cap\">\r\n");
      out.write("									<p>“I am at an age where I just want to be fit and healthy\r\n");
      out.write("										our bodies are our responsibility! So start caring for your\r\n");
      out.write("										body and it will care for you. Eat clean it will care for you\r\n");
      out.write("										and workout hard.”</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Single Testimonial -->\r\n");
      out.write("						<div class=\"single-testimonial text-center\">\r\n");
      out.write("							<!-- Testimonial Content -->\r\n");
      out.write("							<div class=\"testimonial-caption \">\r\n");
      out.write("								<!-- founder -->\r\n");
      out.write("								<div class=\"testimonial-founder  \">\r\n");
      out.write("									<div class=\"founder-img mb-30\">\r\n");
      out.write("										<img src=\"");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("											alt=\"\"/> <span>Margaret Lawson</span>\r\n");
      out.write("										<p>Creative Director</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"testimonial-top-cap\">\r\n");
      out.write("									<p>“I am at an age where I just want to be fit and healthy\r\n");
      out.write("										our bodies are our responsibility! So start caring for your\r\n");
      out.write("										body and it will care for you. Eat clean it will care for you\r\n");
      out.write("										and workout hard.”</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- Single Testimonial -->\r\n");
      out.write("						<div class=\"single-testimonial text-center\">\r\n");
      out.write("							<!-- Testimonial Content -->\r\n");
      out.write("							<div class=\"testimonial-caption \">\r\n");
      out.write("								<!-- founder -->\r\n");
      out.write("								<div class=\"testimonial-founder  \">\r\n");
      out.write("									<div class=\"founder-img mb-30\">\r\n");
      out.write("										<img src=\"");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("											alt=\"\"/> <span>Margaret Lawson</span>\r\n");
      out.write("										<p>Creative Director</p>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"testimonial-top-cap\">\r\n");
      out.write("									<p>“I am at an age where I just want to be fit and healthy\r\n");
      out.write("										our bodies are our responsibility! So start caring for your\r\n");
      out.write("										body and it will care for you. Eat clean it will care for you\r\n");
      out.write("										and workout hard.”</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Testimonial End --> <!-- Support Company Start-->\r\n");
      out.write("	<div class=\"support-company-area support-padding fix\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row align-items-center\">\r\n");
      out.write("				<div class=\"col-xl-6 col-lg-6\">\r\n");
      out.write("					<div class=\"right-caption\">\r\n");
      out.write("						<!-- Section Tittle -->\r\n");
      out.write("						<div class=\"section-tittle section-tittle2\">\r\n");
      out.write("							<span>What we are doing</span>\r\n");
      out.write("							<h2>24k Talented people are getting Jobs</h2>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"support-caption\">\r\n");
      out.write("							<p class=\"pera-top\">Mollit anim laborum duis au dolor in\r\n");
      out.write("								voluptate velit ess cillum dolore eu lore dsu quality mollit\r\n");
      out.write("								anim laborumuis au dolor in voluptate velit cillum.</p>\r\n");
      out.write("							<p>Mollit anim laborum.Duis aute irufg dhjkolohr in re\r\n");
      out.write("								voluptate velit esscillumlore eu quife nrulla parihatur.\r\n");
      out.write("								Excghcepteur signjnt occa cupidatat non inulpadeserunt mollit\r\n");
      out.write("								aboru. temnthp incididbnt ut labore mollit anim laborum suis\r\n");
      out.write("								aute.</p>\r\n");
      out.write("							<a href=\"about.html\" class=\"btn post-btn\">Post a job</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-6 col-lg-6\">\r\n");
      out.write("					<div class=\"support-location-img\">\r\n");
      out.write("						<img src=\"");
      if (_jspx_meth_c_005furl_005f10(_jspx_page_context))
        return;
      out.write("\" alt=\"\"/>\r\n");
      out.write("						<div class=\"support-img-cap text-center\">\r\n");
      out.write("							<p>Since</p>\r\n");
      out.write("							<span>1994</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Support Company End--> <!-- Blog Area Start -->\r\n");
      out.write("	<div class=\"home-blog-area blog-h-padding\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<!-- Section Tittle -->\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-12\">\r\n");
      out.write("					<div class=\"section-tittle text-center\">\r\n");
      out.write("						<span>Our latest blog</span>\r\n");
      out.write("						<h2>Our recent news</h2>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-xl-6 col-lg-6 col-md-6\">\r\n");
      out.write("					<div class=\"home-blog-single mb-30\">\r\n");
      out.write("						<div class=\"blog-img-cap\">\r\n");
      out.write("							<div class=\"blog-img\">\r\n");
      out.write("								<img src=\"");
      if (_jspx_meth_c_005furl_005f11(_jspx_page_context))
        return;
      out.write("\" alt=\"\"/>\r\n");
      out.write("								<!-- Blog date -->\r\n");
      out.write("								<div class=\"blog-date text-center\">\r\n");
      out.write("									<span>24</span>\r\n");
      out.write("									<p>Now</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"blog-cap\">\r\n");
      out.write("								<p>| Properties</p>\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"single-blog.html\">Footprints in Time is perfect\r\n");
      out.write("										House in Kurashiki</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<a href=\"#\" class=\"more-btn\">Read more »</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-xl-6 col-lg-6 col-md-6\">\r\n");
      out.write("					<div class=\"home-blog-single mb-30\">\r\n");
      out.write("						<div class=\"blog-img-cap\">\r\n");
      out.write("							<div class=\"blog-img\">\r\n");
      out.write("								<img src=\"");
      if (_jspx_meth_c_005furl_005f12(_jspx_page_context))
        return;
      out.write("\"/>\r\n");
      out.write("								<!-- Blog date -->\r\n");
      out.write("								<div class=\"blog-date text-center\">\r\n");
      out.write("									<span>24</span>\r\n");
      out.write("									<p>Now</p>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"blog-cap\">\r\n");
      out.write("								<p>| Properties</p>\r\n");
      out.write("								<h3>\r\n");
      out.write("									<a href=\"single-blog.html\">Footprints in Time is perfect\r\n");
      out.write("										House in Kurashiki</a>\r\n");
      out.write("								</h3>\r\n");
      out.write("								<a href=\"#\" class=\"more-btn\">Read more »</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/web/home.jsp(15,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/assets/img/hero/h1_hero.jpg");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/web/home.jsp(185,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/assets/img/gallery/cv_bg.jpg");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /views/web/home.jsp(217,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/assets/img/icon/job-list1.png");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /views/web/home.jsp(237,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/assets/img/icon/job-list2.png");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /views/web/home.jsp(257,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/assets/img/icon/job-list3.png");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /views/web/home.jsp(277,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/assets/img/icon/job-list4.png");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /views/web/home.jsp(298,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/assets/img/gallery/how-applybg.png");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /views/web/home.jsp(364,20) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/assets/img/testmonial/testimonial-founder.png");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /views/web/home.jsp(384,20) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/assets/img/testmonial/testimonial-founder.png");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /views/web/home.jsp(404,20) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/assets/img/testmonial/testimonial-founder.png");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent(null);
      // /views/web/home.jsp(448,16) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/assets/img/service/support-img.jpg");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f11 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f11_reused = false;
    try {
      _jspx_th_c_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f11.setParent(null);
      // /views/web/home.jsp(475,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f11.setValue("/assets/img/blog/home-blog1.jpg");
      int _jspx_eval_c_005furl_005f11 = _jspx_th_c_005furl_005f11.doStartTag();
      if (_jspx_th_c_005furl_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f11);
      _jspx_th_c_005furl_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f11, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f12 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f12_reused = false;
    try {
      _jspx_th_c_005furl_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f12.setParent(null);
      // /views/web/home.jsp(497,18) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f12.setValue("/assets/img/blog/home-blog2.jpg\" alt=");
      int _jspx_eval_c_005furl_005f12 = _jspx_th_c_005furl_005f12.doStartTag();
      if (_jspx_th_c_005furl_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f12);
      _jspx_th_c_005furl_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f12, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f12_reused);
    }
    return false;
  }
}
