/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-03 05:58:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class job_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1712144786899L));
    _jspx_dependants.put("jar:file:/D:/PBL3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PBL3/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("jar:file:/D:/PBL3/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PBL3/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1711982526419L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1712141790945L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Admin - All Jobs</title>\r\n");
      out.write("<!-- paginator \r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style media=\"screen\" type=\"text/css\">\r\n");
      out.write("legend {\r\n");
      out.write("	padding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<style media=\"screen\" type=\"text/css\">\r\n");
      out.write("legend {\r\n");
      out.write("	padding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<!-- <form action=\"/PBL3/admin-job\" id=\"formSubmit\" method=\"post\"> -->\r\n");
      out.write("	<main> <!-- Hero Area End --> <!-- Job List Area Start -->\r\n");
      out.write("	<div class=\"job-listing-area pt-120 pb-120\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<!-- Left content -->\r\n");
      out.write("				<div class=\"col-xl-3 col-lg-3 col-md-4\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("						<div class=\"col-12\">\r\n");
      out.write("							<div class=\"small-section-tittle2 mb-45\">\r\n");
      out.write("								<div class=\"ion\">\r\n");
      out.write("									<svg xmlns=\"http://www.w3.org/2000/svg\"\r\n");
      out.write("										xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"20px\"\r\n");
      out.write("										height=\"12px\">\r\n");
      out.write("                                    <path fill-rule=\"evenodd\"\r\n");
      out.write("											fill=\"rgb(27, 207, 107)\"\r\n");
      out.write("											d=\"M7.778,12.000 L12.222,12.000 L12.222,10.000 L7.778,10.000 L7.778,12.000 ZM-0.000,-0.000 L-0.000,2.000 L20.000,2.000 L20.000,-0.000 L-0.000,-0.000 ZM3.333,7.000 L16.667,7.000 L16.667,5.000 L3.333,5.000 L3.333,7.000 Z\" />\r\n");
      out.write("                                    </svg>\r\n");
      out.write("								</div>\r\n");
      out.write("								<h4>Filter Jobs</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Job Category Listing start -->\r\n");
      out.write("					<div class=\"job-category-listing mb-50\">\r\n");
      out.write("						<!-- single one -->\r\n");
      out.write("						<div class=\"single-listing\">\r\n");
      out.write("							<div class=\"small-section-tittle2\">\r\n");
      out.write("								<h4>Job Category</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- Select job items start -->\r\n");
      out.write("							<div class=\"select-job-items2\">\r\n");
      out.write("								<select name=\"select\">\r\n");
      out.write("									<option value=\"\">All Category</option>\r\n");
      out.write("									<option value=\"\">Category 1</option>\r\n");
      out.write("									<option value=\"\">Category 2</option>\r\n");
      out.write("									<option value=\"\">Category 3</option>\r\n");
      out.write("									<option value=\"\">Category 4</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!--  Select job items End-->\r\n");
      out.write("							<!-- select-Categories start -->\r\n");
      out.write("							<div class=\"select-Categories pt-80 pb-50\">\r\n");
      out.write("								<div class=\"small-section-tittle2\">\r\n");
      out.write("									<h4>Job Type</h4>\r\n");
      out.write("								</div>\r\n");
      out.write("								<label class=\"container\">Full Time <input\r\n");
      out.write("									type=\"checkbox\"> <span class=\"checkmark\"></span>\r\n");
      out.write("								</label> <label class=\"container\">Part Time <input\r\n");
      out.write("									type=\"checkbox\" checked=\"checked active\"> <span\r\n");
      out.write("									class=\"checkmark\"></span>\r\n");
      out.write("								</label> <label class=\"container\">Remote <input type=\"checkbox\">\r\n");
      out.write("									<span class=\"checkmark\"></span>\r\n");
      out.write("								</label> <label class=\"container\">Freelance <input\r\n");
      out.write("									type=\"checkbox\"> <span class=\"checkmark\"></span>\r\n");
      out.write("								</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- select-Categories End -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- single two -->\r\n");
      out.write("						<div class=\"single-listing\">\r\n");
      out.write("							<div class=\"small-section-tittle2\">\r\n");
      out.write("								<h4>Job Location</h4>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- Select job items start -->\r\n");
      out.write("							<div class=\"select-job-items2\">\r\n");
      out.write("								<select name=\"select\">\r\n");
      out.write("									<option value=\"\">Anywhere</option>\r\n");
      out.write("									<option value=\"\">Category 1</option>\r\n");
      out.write("									<option value=\"\">Category 2</option>\r\n");
      out.write("									<option value=\"\">Category 3</option>\r\n");
      out.write("									<option value=\"\">Category 4</option>\r\n");
      out.write("									<option value=\"\">Category 5</option>\r\n");
      out.write("									<option value=\"\">Category 6</option>\r\n");
      out.write("									<option value=\"\">Category 7</option>\r\n");
      out.write("									<option value=\"\">Category 8</option>\r\n");
      out.write("									<option value=\"\">Category 9</option>\r\n");
      out.write("									<option value=\"\">Category 10</option>\r\n");
      out.write("									<option value=\"\">Category 11</option>\r\n");
      out.write("									<option value=\"\">Category 12</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!--  Select job items End-->\r\n");
      out.write("							<!-- select-Categories start -->\r\n");
      out.write("							<div class=\"select-Categories pt-80 pb-50\">\r\n");
      out.write("								<div class=\"small-section-tittle2\">\r\n");
      out.write("									<h4>Experience</h4>\r\n");
      out.write("								</div>\r\n");
      out.write("								<label class=\"container\">1-2 Years <input\r\n");
      out.write("									type=\"checkbox\"> <span class=\"checkmark\"></span>\r\n");
      out.write("								</label> <label class=\"container\">2-3 Years <input\r\n");
      out.write("									type=\"checkbox\" checked=\"checked active\"> <span\r\n");
      out.write("									class=\"checkmark\"></span>\r\n");
      out.write("								</label> <label class=\"container\">3-6 Years <input\r\n");
      out.write("									type=\"checkbox\"> <span class=\"checkmark\"></span>\r\n");
      out.write("								</label> <label class=\"container\">6-more.. <input\r\n");
      out.write("									type=\"checkbox\"> <span class=\"checkmark\"></span>\r\n");
      out.write("								</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- select-Categories End -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<!-- single three -->\r\n");
      out.write("						<div class=\"single-listing\">\r\n");
      out.write("							<!-- select-Categories start -->\r\n");
      out.write("							<div class=\"select-Categories pb-50\">\r\n");
      out.write("								<div class=\"small-section-tittle2\">\r\n");
      out.write("									<h4>Posted Within</h4>\r\n");
      out.write("								</div>\r\n");
      out.write("								<label class=\"container\">Any <input type=\"checkbox\">\r\n");
      out.write("									<span class=\"checkmark\"></span>\r\n");
      out.write("								</label> <label class=\"container\">Today <input type=\"checkbox\"\r\n");
      out.write("									checked=\"checked active\"> <span class=\"checkmark\"></span>\r\n");
      out.write("								</label> <label class=\"container\">Last 2 days <input\r\n");
      out.write("									type=\"checkbox\"> <span class=\"checkmark\"></span>\r\n");
      out.write("								</label> <label class=\"container\">Last 3 days <input\r\n");
      out.write("									type=\"checkbox\"> <span class=\"checkmark\"></span>\r\n");
      out.write("								</label> <label class=\"container\">Last 5 days <input\r\n");
      out.write("									type=\"checkbox\"> <span class=\"checkmark\"></span>\r\n");
      out.write("								</label> <label class=\"container\">Last 10 days <input\r\n");
      out.write("									type=\"checkbox\"> <span class=\"checkmark\"></span>\r\n");
      out.write("								</label>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- select-Categories End -->\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"single-listing\">\r\n");
      out.write("							<!-- Range Slider Start -->\r\n");
      out.write("							<aside\r\n");
      out.write("								class=\"left_widgets p_filter_widgets price_rangs_aside sidebar_box_shadow\">\r\n");
      out.write("								<div class=\"small-section-tittle2\">\r\n");
      out.write("									<h4>Filter Jobs</h4>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"widgets_inner\">\r\n");
      out.write("									<div class=\"range_item\">\r\n");
      out.write("										<!-- <div id=\"slider-range\"></div> -->\r\n");
      out.write("										<input type=\"text\" class=\"js-range-slider\" value=\"\" />\r\n");
      out.write("										<div class=\"d-flex align-items-center\">\r\n");
      out.write("											<div class=\"price_text\">\r\n");
      out.write("												<p>Price :</p>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"price_value d-flex justify-content-center\">\r\n");
      out.write("												<input type=\"text\" class=\"js-input-from\" id=\"amount\"\r\n");
      out.write("													readonly /> <span>to</span> <input type=\"text\"\r\n");
      out.write("													class=\"js-input-to\" id=\"amount\" readonly />\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</aside>\r\n");
      out.write("							<!-- Range Slider End -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Job Category Listing End -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- Right content -->\r\n");
      out.write("				<div class=\"col-xl-9 col-lg-9 col-md-8\">\r\n");
      out.write("					<!-- Featured_job_start -->\r\n");
      out.write("					<section class=\"featured-job-area\">\r\n");
      out.write("						<div class=\"container\">\r\n");
      out.write("							<!-- Count of Job list Start -->\r\n");
      out.write("							<div class=\"row\">\r\n");
      out.write("								<div class=\"col-lg-12\">\r\n");
      out.write("									<div class=\"count-job mb-35\">\r\n");
      out.write("										<span>39, 782 Jobs found</span>\r\n");
      out.write("										<!-- Select job items start -->\r\n");
      out.write("										<div class=\"select-job-items\">\r\n");
      out.write("											<span>Sort by</span> <select name=\"select\">\r\n");
      out.write("												<option value=\"\">None</option>\r\n");
      out.write("												<option value=\"\">job list</option>\r\n");
      out.write("												<option value=\"\">job list</option>\r\n");
      out.write("												<option value=\"\">job list</option>\r\n");
      out.write("											</select>\r\n");
      out.write("										</div>\r\n");
      out.write("										<!--  Select job items End-->\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- Count of Job list End -->\r\n");
      out.write("							<!-- single-job-content -->\r\n");
      out.write("							<div class=\"single-job-items mb-30\">\r\n");
      out.write("								<div class=\"job-items\">\r\n");
      out.write("									<div class=\"company-img\">\r\n");
      out.write("										<a href=\"#\"><img src=\"assets/img/icon/job-list1.png\"\r\n");
      out.write("											alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"job-tittle job-tittle2\">\r\n");
      out.write("										<a href=\"#\">\r\n");
      out.write("											<h4>Digital Marketer</h4>\r\n");
      out.write("										</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li>Creative Agency</li>\r\n");
      out.write("											<li><i class=\"fas fa-map-marker-alt\"></i>Athens, Greece</li>\r\n");
      out.write("											<li>$3500 - $4000</li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"items-link items-link2 f-right\">\r\n");
      out.write("									<a href=\"job_details.html\">Full Time</a> <span>7 hours\r\n");
      out.write("										ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- single-job-content -->\r\n");
      out.write("							<div class=\"single-job-items mb-30\">\r\n");
      out.write("								<div class=\"job-items\">\r\n");
      out.write("									<div class=\"company-img\">\r\n");
      out.write("										<a href=\"#\"><img src=\"assets/img/icon/job-list2.png\"\r\n");
      out.write("											alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"job-tittle job-tittle2\">\r\n");
      out.write("										<a href=\"#\">\r\n");
      out.write("											<h4>Digital Marketer</h4>\r\n");
      out.write("										</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li>Creative Agency</li>\r\n");
      out.write("											<li><i class=\"fas fa-map-marker-alt\"></i>Athens, Greece</li>\r\n");
      out.write("											<li>$3500 - $4000</li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"items-link items-link2 f-right\">\r\n");
      out.write("									<a href=\"job_details.html\">Full Time</a> <span>7 hours\r\n");
      out.write("										ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- single-job-content -->\r\n");
      out.write("							<div class=\"single-job-items mb-30\">\r\n");
      out.write("								<div class=\"job-items\">\r\n");
      out.write("									<div class=\"company-img\">\r\n");
      out.write("										<a href=\"#\"><img src=\"assets/img/icon/job-list3.png\"\r\n");
      out.write("											alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"job-tittle job-tittle2\">\r\n");
      out.write("										<a href=\"#\">\r\n");
      out.write("											<h4>Digital Marketer</h4>\r\n");
      out.write("										</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li>Creative Agency</li>\r\n");
      out.write("											<li><i class=\"fas fa-map-marker-alt\"></i>Athens, Greece</li>\r\n");
      out.write("											<li>$3500 - $4000</li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"items-link items-link2 f-right\">\r\n");
      out.write("									<a href=\"job_details.html\">Full Time</a> <span>7 hours\r\n");
      out.write("										ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- single-job-content -->\r\n");
      out.write("							<div class=\"single-job-items mb-30\">\r\n");
      out.write("								<div class=\"job-items\">\r\n");
      out.write("									<div class=\"company-img\">\r\n");
      out.write("										<a href=\"#\"><img src=\"assets/img/icon/job-list4.png\"\r\n");
      out.write("											alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"job-tittle job-tittle2\">\r\n");
      out.write("										<a href=\"#\">\r\n");
      out.write("											<h4>Digital Marketer</h4>\r\n");
      out.write("										</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li>Creative Agency</li>\r\n");
      out.write("											<li><i class=\"fas fa-map-marker-alt\"></i>Athens, Greece</li>\r\n");
      out.write("											<li>$3500 - $4000</li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"items-link items-link2 f-right\">\r\n");
      out.write("									<a href=\"job_details.html\">Full Time</a> <span>7 hours\r\n");
      out.write("										ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- single-job-content -->\r\n");
      out.write("							<div class=\"single-job-items mb-30\">\r\n");
      out.write("								<div class=\"job-items\">\r\n");
      out.write("									<div class=\"company-img\">\r\n");
      out.write("										<a href=\"#\"><img src=\"assets/img/icon/job-list1.png\"\r\n");
      out.write("											alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"job-tittle job-tittle2\">\r\n");
      out.write("										<a href=\"#\">\r\n");
      out.write("											<h4>Digital Marketer</h4>\r\n");
      out.write("										</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li>Creative Agency</li>\r\n");
      out.write("											<li><i class=\"fas fa-map-marker-alt\"></i>Athens, Greece</li>\r\n");
      out.write("											<li>$3500 - $4000</li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"items-link items-link2 f-right\">\r\n");
      out.write("									<a href=\"job_details.html\">Full Time</a> <span>7 hours\r\n");
      out.write("										ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- single-job-content -->\r\n");
      out.write("							<div class=\"single-job-items mb-30\">\r\n");
      out.write("								<div class=\"job-items\">\r\n");
      out.write("									<div class=\"company-img\">\r\n");
      out.write("										<a href=\"#\"><img\r\n");
      out.write("											src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/icon/job-list3.png\"\r\n");
      out.write("											alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"job-tittle job-tittle2\">\r\n");
      out.write("										<a href=\"#\">\r\n");
      out.write("											<h4>Digital Marketer</h4>\r\n");
      out.write("										</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li>Creative Agency</li>\r\n");
      out.write("											<li><i class=\"fas fa-map-marker-alt\"></i>Athens, Greece</li>\r\n");
      out.write("											<li>$3500 - $4000</li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"items-link items-link2 f-right\">\r\n");
      out.write("									<a href=\"job_details.html\">Full Time</a> <span>7 hours\r\n");
      out.write("										ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!-- single-job-content -->\r\n");
      out.write("							<div class=\"single-job-items mb-30\">\r\n");
      out.write("								<div class=\"job-items\">\r\n");
      out.write("									<div class=\"company-img\">\r\n");
      out.write("										<a href=\"#\"><img\r\n");
      out.write("											src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/icon/job-list4.png\"\r\n");
      out.write("											alt=\"\"></a>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"job-tittle job-tittle2\">\r\n");
      out.write("										<a href=\"#\">\r\n");
      out.write("											<h4>Digital Marketer</h4>\r\n");
      out.write("										</a>\r\n");
      out.write("										<ul>\r\n");
      out.write("											<li>Creative Agency</li>\r\n");
      out.write("											<li><i class=\"fas fa-map-marker-alt\"></i>Athens, Greece</li>\r\n");
      out.write("											<li>$3500 - $4000</li>\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"items-link items-link2 f-right\">\r\n");
      out.write("									<a href=\"job_details.html\">Full Time</a> <span>7 hours\r\n");
      out.write("										ago</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</section>\r\n");
      out.write("					<!-- Featured_job_end -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- Job List Area End --> <!--Pagination Start  \r\n");
      out.write("	<div class=\"pagination-area pb-115 text-center\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-xl-12\">\r\n");
      out.write("					<div class=\"single-wrap d-flex justify-content-center\">\r\n");
      out.write("						<nav aria-label=\"Page navigation example\">\r\n");
      out.write("							<ul class=\"pagination justify-content-start\">\r\n");
      out.write("								<li class=\"page-item active\"><a class=\"page-link\" href=\"#\">01</a></li>\r\n");
      out.write("								<li class=\"page-item\"><a class=\"page-link\" href=\"#\">02</a></li>\r\n");
      out.write("								<li class=\"page-item\"><a class=\"page-link\" href=\"#\">03</a></li>\r\n");
      out.write("								<li class=\"page-item\"><a class=\"page-link\" href=\"#\"><span\r\n");
      out.write("										class=\"ti-angle-right\"></span></a></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</nav>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	--> <!--Pagination End  --> <!--  Pagiantor -->\r\n");
      out.write("	<div class=\"pagination-area pb-115 text-center\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-xl-12\">\r\n");
      out.write("					<div class=\"single-wrap d-flex justify-content-center\">\r\n");
      out.write("						<nav aria-label=\"Page navigation example\">\r\n");
      out.write("							<div id=\"pagination\" class=\"text-center\"></div>\r\n");
      out.write("							<input type=\"hidden\" value=\"\" id=\"page\" name=\"page\"/> \r\n");
      out.write("							\r\n");
      out.write("						</nav>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</main>\r\n");
      out.write("	<!-- </form> -->\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/paginator/simple-bootstrap-paginator.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		var pag = $('#pagination').simplePaginator({\r\n");
      out.write("			totalPages : 30,\r\n");
      out.write("			visiblePages: 5,\r\n");
      out.write("			pageChange : function(page) {\r\n");
      out.write("				// $('#').empty().text('Page is ' + page);\r\n");
      out.write("				$('#page').val(page);\r\n");
      out.write("				$('#formSubmit').submit();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
